# Site settings
title: Computational Science and Engineering
email: "[first_name(without caps)].[last_name(without caps)][at]utah.edu"
description: "Everything High Performance"
baseurl: "/Computational-Sciences"
url: "http://tgautam03.github.io/"
#twitter_username:
github_username:  tgautam03

# Build settings
# remote_theme: pdmosses/just-the-docs@combination-rec-nav
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
